-- MySQL Script generated by MySQL Workbench
-- Wed May 16 03:32:16 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema autionweb_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `autionweb_db` ;

-- -----------------------------------------------------
-- Schema autionweb_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `autionweb_db` DEFAULT CHARACTER SET utf8 ;
USE `autionweb_db` ;

-- -----------------------------------------------------
-- Table `autionweb_db`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autionweb_db`.`admin` ;

CREATE TABLE IF NOT EXISTS `autionweb_db`.`admin` (
  `idAdmin` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(128) NULL DEFAULT NULL,
  `password` VARCHAR(128) NULL DEFAULT NULL,
  PRIMARY KEY (`idAdmin`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `autionweb_db`.`camdaugia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autionweb_db`.`camdaugia` ;

CREATE TABLE IF NOT EXISTS `autionweb_db`.`camdaugia` (
  `idNguoiDung` INT(11) NOT NULL,
  `idSanPham` INT(11) NOT NULL,
  PRIMARY KEY (`idNguoiDung`, `idSanPham`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `autionweb_db`.`chitietdanhgia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autionweb_db`.`chitietdanhgia` ;

CREATE TABLE IF NOT EXISTS `autionweb_db`.`chitietdanhgia` (
  `idSanPham` INT(11) NOT NULL,
  `idNguoiDanhGia` INT(11) NOT NULL,
  `idNguoiDuocDanhGia` INT(11) NOT NULL,
  `congHayTru` TINYINT(4) NULL DEFAULT NULL,
  `nhanXet` VARCHAR(2048) NULL DEFAULT NULL,
  `thoiDiemDanhGia` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`idSanPham`, `idNguoiDanhGia`, `idNguoiDuocDanhGia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `autionweb_db`.`danhsachdaugia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autionweb_db`.`danhsachdaugia` ;

CREATE TABLE IF NOT EXISTS `autionweb_db`.`danhsachdaugia` (
  `idSanPham` INT(11) NOT NULL,
  `idNguoiDung` INT(11) NOT NULL,
  PRIMARY KEY (`idSanPham`, `idNguoiDung`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `autionweb_db`.`danhsachyeuthich`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autionweb_db`.`danhsachyeuthich` ;

CREATE TABLE IF NOT EXISTS `autionweb_db`.`danhsachyeuthich` (
  `idSanPham` INT(11) NOT NULL,
  `idNguoiDung` INT(11) NOT NULL,
  PRIMARY KEY (`idSanPham`, `idNguoiDung`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `autionweb_db`.`lichsumota`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autionweb_db`.`lichsumota` ;

CREATE TABLE IF NOT EXISTS `autionweb_db`.`lichsumota` (
  `idSanPham` INT(11) NOT NULL,
  `thoiDiemCapNhat` DATETIME NOT NULL,
  `noiDungCapNhat` VARCHAR(2048) NULL DEFAULT NULL,
  PRIMARY KEY (`idSanPham`, `thoiDiemCapNhat`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `autionweb_db`.`lichsuragia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autionweb_db`.`lichsuragia` ;

CREATE TABLE IF NOT EXISTS `autionweb_db`.`lichsuragia` (
  `idSanPham` INT(11) NOT NULL,
  `idNguoiDung` INT(11) NOT NULL,
  `thoiDiemRaGia` DATETIME NOT NULL,
  `giaDau` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idSanPham`, `idNguoiDung`, `thoiDiemRaGia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `autionweb_db`.`loai`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autionweb_db`.`loai` ;

CREATE TABLE IF NOT EXISTS `autionweb_db`.`loai` (
  `idLoaiSanPham` INT(11) NOT NULL AUTO_INCREMENT,
  `tenLoaiSanPham` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idLoaiSanPham`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `autionweb_db`.`nguoidung`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autionweb_db`.`nguoidung` ;

CREATE TABLE IF NOT EXISTS `autionweb_db`.`nguoidung` (
  `idNguoiDung` INT(11) NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(128) NULL DEFAULT NULL,
  `hoTen` VARCHAR(45) NULL DEFAULT NULL,
  `diaChi` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NOT NULL,
  `diemDanhGiaCong` INT(11) NULL DEFAULT '0',
  `diemDanhGiaTru` INT(11) NULL DEFAULT '0',
  `viTri` TINYINT(1) NULL DEFAULT NULL,
  `coQuyenBan` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`idNguoiDung`, `email`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `autionweb_db`.`nguoidungxinban`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autionweb_db`.`nguoidungxinban` ;

CREATE TABLE IF NOT EXISTS `autionweb_db`.`nguoidungxinban` (
  `idNguoiDung` INT(11) NOT NULL,
  `thoiDiemXinBan` DATETIME NOT NULL,
  PRIMARY KEY (`idNguoiDung`, `thoiDiemXinBan`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `autionweb_db`.`sanpham`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autionweb_db`.`sanpham` ;

CREATE TABLE IF NOT EXISTS `autionweb_db`.`sanpham` (
  `idSanPham` INT(11) NOT NULL AUTO_INCREMENT,
  `tenSanPham` VARCHAR(255) NULL DEFAULT NULL,
  `giaHienTai` INT(11) NULL DEFAULT NULL,
  `giaMuaNgay` INT(11) NULL DEFAULT NULL,
  `idNguoiBan` INT(11) NULL DEFAULT NULL,
  `idNguoiGiaCaoNhat` INT(11) NULL DEFAULT NULL,
  `thoiDiemDang` DATETIME NULL DEFAULT NULL,
  `thoiDiemKetThuc` DATETIME NULL DEFAULT NULL,
  `buocGia` INT(11) NULL DEFAULT NULL,
  `moTa` VARCHAR(2048) NULL DEFAULT NULL,
  `tinhTrang` INT(11) NULL DEFAULT NULL,
  `luotBid` INT(11) NULL DEFAULT NULL,
  `loai` INT(11) NULL DEFAULT NULL,
  `tuDongGiaHan` INT(11) NULL DEFAULT '0',
  PRIMARY KEY (`idSanPham`))
ENGINE = InnoDB
AUTO_INCREMENT = 52
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `autionweb_db`.`sessions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autionweb_db`.`sessions` ;

CREATE TABLE IF NOT EXISTS `autionweb_db`.`sessions` (
  `session_id` VARCHAR(128) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NOT NULL,
  `expires` INT(11) UNSIGNED NOT NULL,
  `data` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NULL DEFAULT NULL,
  PRIMARY KEY (`session_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
